name: Brew Install

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - 'Formula/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Setup Path
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.bash_profile
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew doctor

    - name: Install Eask CLI
      run: |
        brew tap emacs-eask/cli https://github.com/emacs-eask/packaging
        brew install eask-cli

    - run: eask --version
