name: Brew Install

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - 'Formula'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Try install
      run: |
        brew tap https://github.com/emacs-eask/packaging
        brew install eask-cli
