name: Debian Release

on:
  workflow_run:
    workflows: ["Debian Build"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

    - name: Package
      working-directory: debian
      run: |
        dpkg-scanpackages --multiversion . > Packages
        gzip -k -f Packages

    - name: Release
      working-directory: debian
      run: |
        apt-ftparchive release . > Release
        gpg --default-key "91179AA1A67CC24B34182F6DD31B19D84B2E120C" -abs -o - Release > Release.gpg
        gpg --default-key "91179AA1A67CC24B34182F6DD31B19D84B2E120C" --clearsign -o - Release > InRelease

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Release Debian package"

    - name: Push updated deb package
      continue-on-error: true
      uses: jcs090218/github-push-action@master
      with:
        branch: master
        rebase: true
        retry: 7
