name: Debian Build

on:
   workflow_run:
    workflows: ["Debian Update"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERSION: 0.8.6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - arm64
        - x64

    steps:
    - uses: actions/checkout@v4

    - name: Update deb package
      working-directory: debian
      run: |
        curl -fsSL https://github.com/emacs-eask/cli/releases/download/${{ env.VERSION }}/eask_${{ env.VERSION }}_linux-${{ matrix.arch }}.zip -o temp.zip
        mkdir -p "$(pwd)/eask_${{ env.VERSION }}_${{ matrix.arch }}/DEBIAN"
        mkdir -p "$(pwd)/eask_${{ env.VERSION }}_${{ matrix.arch }}/usr/local/bin"
        cp control/${{ matrix.arch }} "$(pwd)/eask_${{ env.VERSION }}_${{ matrix.arch }}/DEBIAN/control"
        unzip temp.zip -d "$(pwd)/eask_${{ env.VERSION }}_${{ matrix.arch }}/usr/local/bin"
        dpkg-deb --build eask_${{ env.VERSION }}_${{ matrix.arch }}

    - name: Clean up
      working-directory: debian
      run: |
        rm -rf temp.zip
        rm -rf eask_${{ env.VERSION }}_${{ matrix.arch }}

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update Debian package"

    - name: Push updated deb package
      continue-on-error: true
      uses: jcs090218/github-push-action@master
      with:
        branch: master
        rebase: true
        retry: 7
