name: Debian Build

on:
  workflow_run:
    workflows: ["Debian Update"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
        - arm64
        - x64

    steps:
    - uses: actions/checkout@v4

    - uses: oprypin/find-latest-tag@v1
      with:
        repository: emacs-eask/cli
        releases-only: true
      id: eask-cli-version

    - name: Expose Version
      run: |
        echo "VERSION=${{ steps.eask-cli-version.outputs.tag }}" >> $GITHUB_ENV

    - name: Expose Arch
      if: matrix.arch == 'x64'
      run: |
        echo "ARCH=amd64" >> $GITHUB_ENV

    - name: Expose Arch
      if: matrix.arch == 'arm64'
      run: |
        echo "ARCH=arm64" >> $GITHUB_ENV

    - name: Update deb package
      working-directory: debian
      run: |
        curl -fsSL https://github.com/emacs-eask/cli/releases/download/${{ env.VERSION }}/eask_${{ env.VERSION }}_linux-${{ matrix.arch }}.zip -o temp.zip
        mkdir -p "$(pwd)/eask_${{ env.VERSION }}_${{ env.ARCH }}/DEBIAN"
        mkdir -p "$(pwd)/eask_${{ env.VERSION }}_${{ env.ARCH }}/usr/local/bin"
        cp control/${{ matrix.arch }} "$(pwd)/eask_${{ env.VERSION }}_${{ env.ARCH }}/DEBIAN/control"
        unzip temp.zip -d "$(pwd)/eask_${{ env.VERSION }}_${{ env.ARCH }}/usr/local/bin"
        dpkg-deb --build eask_${{ env.VERSION }}_${{ env.ARCH }}

    - name: Clean up
      working-directory: debian
      run: |
        rm -rf temp.zip
        rm -rf eask_${{ env.VERSION }}_${{ env.ARCH }}

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update Debian package"

    - name: Push updated deb package
      continue-on-error: true
      uses: jcs090218/github-push-action@master
      with:
        branch: master
        rebase: true
        retry: 7
