name: Debian Release

on:
  workflow_run:
    workflows: ["Debian Build"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Package
      working-directory: debian
      run: |
        dpkg-scanpackages --multiversion . > Packages
        gzip -k -f Packages

    - name: Release
      working-directory: debian
      run: |
        apt-ftparchive release . > Release
        gpg --default-key "jcs090218@gmail.com" -abs -o - Release > Release.gpg
        gpg --default-key "jcs090218@gmail.com" --clearsign -o - Release > InRelease

    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update Debian package"

    - name: Push updated deb package
      continue-on-error: true
      uses: jcs090218/github-push-action@master
      with:
        branch: master
        rebase: true
        retry: 7
