name: Port Check

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - 'macports/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MacPorts
      run: |
        curl -LO https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci
        source ./macports-ci install

    - name: Test
      working-directory: macports
      run: |
        port lint
        port -vst install
