name: Port Check

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - 'macports/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PKG: MacPorts-2.8.1-12-Monterey.pkg

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install MacPorts
      run: |
        wget https://github.com/macports/macports-base/releases/download/v2.8.1/${{ env.PKG }}
        sudo installer -pkg ./${{ env.PKG }} -target /

    - name: Test
      working-directory: macports
      run: |
        port lint
        port -vst install
