name: Port Check

on:
  push:
    branches:
      - master
    paths:
      - '**.yml'
      - 'macports/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install MacPorts
      uses: melusina-org/setup-macports@v1.1.4
      with:
        version: '2.10.1'

    - uses: actions/checkout@v4

    - name: Copy Portfile to ~/
      run: |
        cp ./macports/Portfile ~/

    - name: Checkout MacPorts
      uses: actions/checkout@v4
      with:
        repository: 'macports/macports-ports'

    - name: Copy Portfile from ~/ to target directory
      run: |
        cp ~/Portfile ./devel/eask-cli/Portfile

    - name: Prepare
      run: |
        sudo port -v install libcxx gnutar xz gzip

    - name: Test
      working-directory: devel/eask-cli/
      continue-on-error: true
      run: |
        sudo port lint --nitpick
        sudo port -vst install

    - name: Show log
      run: |
        cat /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_pkgconfig/pkgconfig/main.log
